### ISSUE TITLE
Change note mode colors

### ISSUE THREAD

**Issue by unremarkablegarden** [mat1jaczyyy/LP-Firmware-Utility#10]
If all I wanted to do was change the default colours of the Note mode, could I do that with this utility? I don't want different colours per velocity...

**Comment by mat1jaczyyy** [comment]
assuming youre talking about lp pro
i mean technically yes, but i'd have to make a specific patch for it and not many people want this soooooooo you should probably just use cfw and then if you want change the colors in the source code and compile it yourself

**Comment by unremarkablegarden** [comment]
thanks! exciting! what's cfw? how do i edit the source code?

**Comment by mat1jaczyyy** [comment]
@unremarkablegarden sorry for late https://github.com/mat1jaczyyy/lpp-performance-cfw/blob/master/src/modes/normal/note.c colors are defined near the top. once you modify the file you'll need to recompile and upload it yourself, instructions in readme of that repository
