### ISSUE TITLE
Doesn't receive palette export from CFW

### ISSUE THREAD

**Issue by mat1jaczyyy** [mat1jaczyyy/LP-Firmware-Utility#11]
LP sends bytes but website don't care

**Comment by Brendonovich** [comment]
bruh idk it shows up in midi monitor but website doesnt detect it

**Comment by vaaski** [comment]
<details>
<summary>probably because you're using react instead of vue</summary>

/s

</details>

**Comment by LaunchpadPhil** [comment]
just saying, its still is broken I cannot upload a palette

**Comment by mat1jaczyyy** [comment]
vaaski shut

**Comment by mat1jaczyyy** [comment]
Fixed by 88029ee941e7c3cff1eef05de738a525e5006c85.
