### ISSUE TITLE
Failed start because of missing "main.css"

### ISSUE THREAD

**Issue by arkitowho** [mat1jaczyyy/LP-Firmware-Utility#56]
Hi, mat!
The new commit can't start server because missing "main.css", the older commit will generate this file when start by postcss, seems like a Bug?
![image](https://github.com/mat1jaczyyy/LP-Firmware-Utility/assets/49297379/9b729db6-4c1c-45f6-8099-2f49c3b1860b)

**Comment by mat1jaczyyy** [comment]
@Brendonovich

**Comment by mat1jaczyyy** [comment]
seems like the new vite system no longer generates main.css

**Comment by Brendonovich** [comment]
Ah yep I'll add it back

**Comment by Brendonovich** [comment]
fixed :)
